# Generated by Django 3.2.5 on 2021-07-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_raiting_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
